Date::DATE_FORMATS[:mm_dd_yy] = '%m-%d-%Y'
Date::DATE_FORMATS[:medium] = '%B %e, %Y'
DateTime::DATE_FORMATS[:mm_dd_yy] = '%m-%d-%Y'
DateTime::DATE_FORMATS[:medium] = '%B %e, %Y'
Time::DATE_FORMATS[:mm_dd_yy] = '%m-%d-%Y'
Time::DATE_FORMATS[:medium] = '%B %e, %Y'
